# Generated by Django 4.1 on 2022-08-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_Id', models.AutoField(primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=50)),
                ('User_Email', models.EmailField(max_length=50)),
                ('User_Designation', models.CharField(max_length=100)),
                ('User_city', models.CharField(max_length=40)),
            ],
        ),
    ]
